Repository Multiwoven/docs, pull requests merged in 2024-09, with the labels that each got.

#94 doc: add screenshots for Aws Sagemaker
  guides/data-integration/sources/aws_sagemaker-model.mdx
Labels: documentation

#100 Feature add security information
  help-and-resources/faqs/security.mdx
  mint.json
Labels: documentation, Review effort [1-5]: 2

#99 Documentation/updates
  .DS_Store
  .gitignore
  guides/ai-activation/Data_Apps.mdx
  guides/ai-activation/Models.mdx
  guides/ai-activation/Sources.mdx
  guides/ai-ml-integration/Data_Apps.mdx
  guides/ai-ml-integration/Models.mdx
  guides/ai-ml-integration/Sources.mdx
  guides/ai-ml-integration/overview.mdx
  mint.json
  release-notes/2024.mdx
  release-notes/June_2024.mdx
  release-notes/May_2024.mdx
Labels: documentation, enhancement, Review effort [1-5]: 2
