Repository Multiwoven/docs, pull requests merged in 2024-10, with the labels that each got.

#96 docs: add documentation for Google Vertex Model
  guides/data-integration/sources/google_vertex-model.mdx
  mint.json
Labels: Review effort [1-5]: 2

#102 doc: ms sql destination connector guide
  guides/data-integration/destinations/database/ms_sql.mdx
  mint.json
Labels: documentation, Review effort [1-5]: 2

#104 chore(CE): add email verification env variable
  open-source/guides/setup/environment-variables.mdx
Labels: documentation, Review effort [1-5]: 1

#105 doc: updated with multiwoven worker host and port
  open-source/guides/setup/helm.mdx
Labels: documentation, Review effort [1-5]: 2
